name: PHP Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        php-version: [ '8.1', '8.2', '8.3', '8.4' ]
        event-driver: [ "", "event", "ev" ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: posix, sockets, pcntl, openssl, parallel, ${{ matrix.event-driver }}

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit
        run: |
          vendor/bin/phpunit \
          --coverage-clover=coverage.xml \
          --log-junit=test-results.xml
        env:
          XDEBUG_MODE: coverage

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: event, pcntl, ev, sockets, posix, mbstring, json, curl
          tools: composer:v2

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Check for syntax errors
        run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --diff --verbose
